import type { Metadata, Viewport } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "VoidHunter.com - Hand Tracking Defense Game",
  description: "Hand-powered cosmic defense game. Use your hands to create a black hole and consume enemy planes before they destroy your shield.",
  // manifest handled by app/manifest.ts
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "VoidHunter",
  },
  themeColor: "#0a0a0a",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Google Analytics */}
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-DW0C344RXQ"></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-DW0C344RXQ');
            `,
          }}
        />

        {/* PWA Meta Tags */}
        {/* manifest link automatically generated by Next.js from app/manifest.ts */}
        <link rel="apple-touch-icon" href="/voidhunter/icons/icon-192.png" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="apple-mobile-web-app-title" content="VoidHunter" />
        <meta name="theme-color" content="#0a0a0a" />

        {/* Google Fonts: Press Start 2P + Oxanium */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Press+Start+2P&family=Oxanium:wght@400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        style={{
          margin: 0,
          padding: 0,
          fontFamily: "var(--font-body)",
          backgroundColor: "#0a0a0a",
          color: "#ffffff",
          touchAction: "manipulation",
        }}
      >
        {children}
      </body>
    </html>
  );
}
